### ISSUE TITLE
Add back-referencing to compress files

### ISSUE THREAD

**Issue by ihatecsv** [BlueStone-Tech-Enterprises/scon#11]
Using an [algorithm for removing duplicate strings](https://en.wikipedia.org/wiki/LZ77_and_LZ78), SCON outputs can be massively reduced in size (depending on the contents of compressed objects).

**Comment by JamesxX** [comment]
Possibly introduce tag as reference to another. This would required a second pass in the deserialization, to find the tag to which it refers. It is very possible that this would also increase the length of a file, if the tag referenced is sufficiently nested.

Another idea could be to implicitly number each entry by order, and to reference by position. this would introduce a limitation on the maximum size of the file.

It is also possible that it introduces ambiguity in how references are interpreted. Is it a copy reference, or something akin to a pointer reference. It wouldn't be possible to introduce 2 separate tags to distinguish between the two, as it is computationally expensive to deduce which one it is at serialization time.

To get around this, it would have to be introduced as a standard that all references be only one type of the above. This might render the format incompatible with some projects.

**Comment by ARitz-Cracker** [comment]
I did the thing
